title: "Atul Kumar Pandey"
tagline: "ML · CV · Quant | IIT-BHU"
description: "Personal portfolio"
url: "https://Atul625-py.github.io"
baseurl: "" # Leave blank for GitHub Pages user site

lang: en
timezone: Asia/Kolkata

remote_theme: cotes2020/jekyll-theme-chirpy

header_pages:
  - projects.html
  - about.html

# Output style for custom SCSS (only if you're using `assets/css/custom.scss`)
sass:
  style: compressed

# Social links
github:
  username: Atul625-py
linkedin:
  username: atul-kumar-pandey-4a4633289
email: atul.kpandey.cse23@itbhu.ac.in

# SEO (optional)
google_site_verification: ""
