title: "Atul Kumar Pandey"
tagline: "ML · CV · Quant | IIT-BHU"
description: "Personal portfolio"
url: "https://atul625-py.github.io"
baseurl: ""

lang: en
timezone: Asia/Kolkata

remote_theme: cotes2020/jekyll-theme-chirpy

header_pages:
  - projects.html
  - about.html

github:
  username: Atul625-py
linkedin:
  username: atul-kumar-pandey-4a4633289
email: atul.kpandey.cse23@itbhu.ac.in

sass:
  style: compressed